version: '3'

services:
  app:
    build: .
    environment:
      - PORT=${PORT}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

  nginx:  
    image: nginx:latest  
    ports:
      - "${PORT}:80"
    depends_on:
      - app
    environment:
      - APP_PORT=${PORT}
    volumes:
      - ./nginx.template.conf:/etc/nginx/nginx.template.conf
      - ./start-nginx.sh:/start-nginx.sh
    command: /start-nginx.sh

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  db_data:
