version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=demo_user
      - DB_PASSWORD=demo_password
      - DB_DATABASE=node_gateways

  nginx:  
    image: nginx:latest  
    ports:
      - "3000:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/conf.d/default.conf:ro
    command: /bin/bash -c "nginx -g 'daemon off;'"

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=demo_password
      - MYSQL_DATABASE=node_gateways
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=demo_password

volumes:
  db_data:
